language: python
python:
  - "3.8"

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env

script:
  - poetry install
  - triggercmd -v
